export {
  appendPaintStagingSlot,
  createDefaultSessionState,
  createSessionStore,
  fillPaintStagingSlot,
  patchPaintStagingBrush,
  reorderPaintStagingSlots,
  setActiveBrushId,
  setActiveEraserId,
  setActiveLayerId,
  setActivePaletteId,
  setActiveSketchId,
  setActiveTool,
  setAgentMode,
  setInteractionBusy,
  setPaintStaging,
  setPaintStagingActiveBrushId,
  setPromptEditorOpen,
  setRenderResultView,
  setCanvasFrameId,
  setSelection,
  coerceGatedToolForCompatibility,
  enterContainerEdit,
  exitContainerEdit,
  enterGroupEdit,
  exitGroupEdit,
  setViewFocus,
  setViewport,
  toggleAgentMode,
  togglePromptEditorOpen,
  toggleRenderResultView,
  requestViewportFit,
  clearViewportFitRequest,
  type SessionStore,
} from './sessionStore';
export {
  applyFocusTransition,
  applySurfaceDefaults,
  applySurfaceResume,
  captureSurfaceResume,
  clearSurfaceResumeEntry,
  surfaceResumeKey,
  writeSurfaceResumeEntry,
} from './surfaceResume';
