/**
 * Headless authoring engine — UI-free.
 *
 * Phase 0: shared store primitive
 * Phase 1: types, DocumentStore, SessionStore, selectors
 * Phase 2: Command runner + patch History
 * Phase 3: Node Commands, selection, clipboard
 * Phase 4: SketchData structure Commands
 * Phase 5: AuthoringWorkspace session wiring + local persistence
 */
export { createAuthoringStore, type AuthoringStore } from './store';

export {
  asCanvasId,
  asDocumentId,
  asGraphId,
  asLayerId,
  asNodeId,
  asStrokeId,
  asSublayerId,
  createId,
  type CanvasId,
  type DocumentId,
  type GraphId,
  type LayerId,
  type NodeId,
  type StrokeId,
  type SublayerId,
} from './ids';

export type {
  ActiveTool,
  Canvas,
  CanvasTextNode,
  CanvasTextStyle,
  DocumentState,
  FrameNode,
  Graph,
  GraphTextNode,
  ImageNode,
  ImagePlacement,
  Layer,
  Node,
  NodeBase,
  NodeRef,
  NodeType,
  OutputNode,
  OutputOwnerType,
  Point2D,
  Rect,
  SessionState,
  SketchData,
  SketchDataByCanvas,
  SketchNode,
  Stroke,
  StrokePoint,
  Sublayer,
  ViewFocus,
  ViewportState,
} from './types';
export { DOCUMENT_SCHEMA_VERSION, nodeRefKey, normalizeLegacyNode } from './types';

export {
  canvasTextForCanvas,
  sketchesForCanvas,
  imagesForCanvas,
  imagesForGraph,
  imageRect,
  canDeleteCanvas,
  canDeleteGraph,
  createDefaultSketchData,
  createDocumentStore,
  createEmptyDocumentWorkingCopy,
  createGraph,
  DEFAULT_SKETCH_ARTBOARD_SIZE,
  deleteCanvas,
  deleteGraph,
  firstCanvasIdForGraph,
  firstGraphId,
  frameCardAspect,
  frameCardRect,
  framesForCanvas,
  framesForGraph,
  graphTextNodes,
  replaceDocument,
  sketchHasPaletteCatalogKeys,
  type CreateEmptyDocumentArgs,
  type DocumentStore,
} from './document';

export {
  createDefaultSessionState,
  createSessionStore,
  setActiveBrushId,
  setActiveEraserId,
  setActiveLayerId,
  setActivePaletteId,
  setActiveSketchId,
  setActiveTool,
  setAgentMode,
  setPromptEditorOpen,
  setRenderResultView,
  setCanvasFrameId,
  setSelection,
  coerceGatedToolForCompatibility,
  setInteractionBusy,
  toggleAgentMode,
  togglePromptEditorOpen,
  toggleRenderResultView,
  setViewFocus,
  setViewport,
  requestViewportFit,
  clearViewportFitRequest,
  clearSurfaceResumeEntry,
  type SessionStore,
} from './session';

export {
  applyForwardPatches,
  applyInversePatches,
  clearHistoryStore,
  createHistoryStore,
  type HistoryEntry,
  type HistoryStore,
} from './history';

export {
  createCommandRunner,
  setCanvasName,
  setNodeVisible,
  type ActivityEvent,
  type Command,
  type CommandRunner,
  type CommandRunnerOptions,
  type DispatchOptions,
} from './commands';

export {
  activateSketch,
  addToSelection,
  buildCanvasText,
  buildFrame,
  buildGraphText,
  buildImage,
  buildOutput,
  buildSketch,
  ensureOutputForOwner,
  canReorderSketchStack,
  canReorderSurfaceStack,
  comparePeerStackOrder,
  clearSelection,
  cloneNodeWithOffset,
  commitCreatedFrame,
  commitCreatedImage,
  commitCreatedSketch,
  commitPaintCreatedSketch,
  editFrameOnCanvas,
  computeSketchStackOrders,
  copyNodes,
  createCanvasText,
  createFrame,
  createGraphText,
  createImage,
  createNode,
  createSketch,
  DEFAULT_DUPLICATE_OFFSET,
  DEFAULT_FRAME_CROP,
  DEFAULT_GRAPH_TEXT_RECT,
  deleteNodes,
  duplicateNodes,
  EMPTY_SKETCH_BOUNDS,
  hasSelectableSketchBounds,
  insertNodes,
  isClipboardPayload,
  isSelected,
  listSketchesForCanvas,
  moveCanvasText,
  moveFrameCrop,
  moveFrameGraph,
  transformFrameGraph,
  moveGraphText,
  moveSketch,
  pasteNodesCommand,
  removeFromSelection,
  reorderSketchStack,
  reorderSurfaceStack,
  moveSketchInStack,
  moveImageInStack,
  moveFrameInStack,
  moveNodeInSurfaceStack,
  listCanvasSurfaceStack,
  listGraphSurfaceStack,
  nextSurfaceStackOrder,
  surfaceStackActionLabel,
  iconForNodeType,
  selectTargetsForFocusedSurface,
  selectTargetLabel,
  addPaletteToSketch,
  appendSketchSlot,
  buildDefaultPaletteSet,
  buildPaletteSetFromSlots,
  clearSketchSlot,
  fillSketchSlot,
  getSketchBrushes,
  getSketchPalette,
  getSketchPalettes,
  paletteSetWithId,
  patchSketchBrush,
  removePaletteFromSketch,
  renameSketchPalette,
  reorderSketchSlots,
  repairSketchPaletteBinds,
  repairSketchPaletteSets,
  resetSketchPaletteToDefault,
  resolvePaintSketchTarget,
  resizeCanvasText,
  resizeFrameCrop,
  resizeGraphText,
  resizeSketch,
  renameFrame,
  renameImage,
  renameSketch,
  setFrameCrop,
  setFramePrompt,
  setFrameResultImageId,
  setFrameWindowUrl,
  landFrameResultImage,
  frameResultImageIds,
  frameResultImageRect,
  frameResultView,
  resolveOutputInputToggleTarget,
  setFrameResultView,
  toggleFrameResultView,
  readImageNaturalSizeFromSrc,
  setImagePrompt,
  setOutputRelativeScale,
  setSketchPrompt,
  isPromptableNodeType,
  compatibleToolsForNodeType,
  isCanvasFrameOutputViewActive,
  isToolGatedByNodeCompatibility,
  selectionAllowsTool,
  hasNodeFocus,
  isNodeFocusType,
  agentFocusOwnerIds,
  agentSoloContentIds,
  chromeForNode,
  chromeForNodeType,
  contextActionsForNodeType,
  intersectContextActions,
  resolveContextMenuModel,
  surfaceContextActions,
  OUTPUT_ACCENT,
  OUTPUT_ORANGE_ACCENT,
  FRAME_OUTPUT_CHROME,
  setNodeLocked,
  setSketchActivePaletteId,
  sketchStackActionLabel,
  toggleSelection,
  transformImageRect,
  transformSketchContents,
  transformContainerContents,
  translateSelectedNodes,
  groupSelection,
  makeContainerFromSketch,
  parseGroupSelection,
  ungroupContainer,
  renameContainer,
  setContainerPrompt,
  expandClipboardNodeIds,
  marqueeCandidatesForFocusedSurface,
  nodesOverlappingMarquee,
  normalizeMarqueeRect,
  rectsOverlap,
  selectionAfterResizeHandleDown,
  selectionForNodeContextMenu,
  nextUntitledFrameName,
  nextUntitledImageNameForCanvas,
  nextUntitledImageNameForGraph,
  nextUntitledSketchName,
  nextRenderResultImageName,
  UNTITLED_FRAME_LABEL,
  UNTITLED_IMAGE_LABEL,
  UNTITLED_SKETCH_LABEL,
  RENDER_RESULT_LABEL,
  type BuildCanvasTextArgs,
  type BuildFrameArgs,
  type BuildGraphTextArgs,
  type BuildImageArgs,
  type BuildOutputArgs,
  type BuildSketchArgs,
  type AuthoringSurface,
  type ClipboardPayload,
  type CommitCreatedFrameArgs,
  type CommitCreatedImageArgs,
  type ContextActionId,
  type ContextMenuRow,
  type NodeChrome,
  type ResolveContextMenuModelArgs,
  type SketchPaletteSet,
  type SketchStackAction,
  type SketchStackOrders,
  type SelectTargetPeerGroup,
  type SelectTargetRow,
} from './nodes';

export {
  addLayer,
  addSublayer,
  artboardRectFromSketch,
  boundsOfSketchPaths,
  BOUNDING_BOX_FIT_PADDING,
  fitSketchVisibleInkBounds,
  paintHullOfSketchPaths,
  pathBelongsToSketch,
  SKETCH_FIT_PADDING,
  VISIBLE_INK_PROBE_MAX_DIM,
  VISIBLE_INK_PROBE_SCALE,
  VISIBLE_INK_PROBE_SLACK,
  clearSketchDrawing,
  commitStroke,
  createCanvasOnGraph,
  reorderLayer,
  reorderSublayer,
  resizeArtboard,
  setLayerLocked,
  setLayerVisible,
  setSublayerLocked,
  setSublayerVisible,
  type CommitStrokeArgs,
  type CreateProbeSurface,
  type FitSketchVisibleInkBoundsOptions,
  type ProbeCanvasContext,
  type ProbeSurface,
} from './sketch';

export {
  createAuthoringWorkspace,
  createLocalStoragePersistenceAdapter,
  deserializeDocument,
  documentPersistenceKey,
  serializeDocument,
  type AuthoringWorkspace,
  type CreateAuthoringWorkspaceOptions,
  type PersistenceAdapter,
} from './workspace';
